# Generated by Django 5.2.7 on 2025-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Публичность'),
        ),
    ]
